# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any, List, Optional

from .._utils.model_base import Model as _Model, rest_field


class ModelFilter(_Model):
    """A filter to apply when searching models.

    :ivar field: The field to filter on. Required.
    :vartype field: str
    :ivar operator: The operator to apply. Required.
    :vartype operator: str
    :ivar values: The values to match. Required.
    :vartype values: list[str]
    """

    field: str = rest_field()
    """The field to filter on. Required."""
    operator: str = rest_field()
    """The operator to apply. Required."""
    values: List[str] = rest_field()
    """The values to match. Required."""


class ModelOrder(_Model):
    """An ordering clause for model search results.

    :ivar field: The field to order by. Required.
    :vartype field: str
    :ivar direction: The direction to order. Known values are: "Asc", "Desc".
    :vartype direction: str
    """

    field: str = rest_field()
    """The field to order by. Required."""
    direction: Optional[str] = rest_field(default=None)
    """The direction to order. Known values are: 'Asc', 'Desc'."""


class ModelSummary(_Model):
    """Summary information about a model in the catalog.

    :ivar popularity: The popularity score of the model.
    :vartype popularity: float
    :ivar name: The name of the model.
    :vartype name: str
    :ivar version: The version of the model.
    :vartype version: str
    :ivar publisher: The publisher of the model.
    :vartype publisher: str
    :ivar registry_name: The registry containing the model.
    :vartype registry_name: str
    :ivar azure_offers: The Azure offer types available for this model.
    :vartype azure_offers: list[str]
    :ivar asset_id: The full asset ID URI.
    :vartype asset_id: str
    :ivar inference_tasks: The inference tasks supported by this model.
    :vartype inference_tasks: list[str]
    """

    popularity: Optional[float] = rest_field(default=None)
    """The popularity score of the model."""
    name: Optional[str] = rest_field(default=None)
    """The name of the model."""
    version: Optional[str] = rest_field(default=None)
    """The version of the model."""
    publisher: Optional[str] = rest_field(default=None)
    """The publisher of the model."""
    registry_name: Optional[str] = rest_field(name="registryName", default=None)
    """The registry containing the model."""
    azure_offers: Optional[List[str]] = rest_field(name="azureOffers", default=None)
    """The Azure offer types available for this model."""
    asset_id: Optional[str] = rest_field(name="assetId", default=None)
    """The full asset ID URI."""
    inference_tasks: Optional[List[str]] = rest_field(name="inferenceTasks", default=None)
    """The inference tasks supported by this model."""


class ModelSearchRequest(_Model):
    """Request body for searching models in the catalog.

    :ivar filters: The filters to apply. Required.
    :vartype filters: list[~azure.ai.catalog.models.ModelFilter]
    :ivar order: The ordering to apply.
    :vartype order: list[~azure.ai.catalog.models.ModelOrder]
    :ivar page_size: The maximum number of results to return.
    :vartype page_size: int
    """

    filters: Optional[List[ModelFilter]] = rest_field(default=None)
    """The filters to apply."""
    order: Optional[List[ModelOrder]] = rest_field(default=None)
    """The ordering to apply."""
    page_size: Optional[int] = rest_field(name="pageSize", default=None)
    """The maximum number of results to return."""


class ModelSearchResponse(_Model):
    """Response from a model search request.

    :ivar total_count: The total number of matching models.
    :vartype total_count: int
    :ivar summaries: The model summaries returned.
    :vartype summaries: list[~azure.ai.catalog.models.ModelSummary]
    """

    total_count: Optional[int] = rest_field(name="totalCount", default=None)
    """The total number of matching models."""
    summaries: Optional[List[ModelSummary]] = rest_field(default=None)
    """The model summaries returned."""
