# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import MutableMapping
import json
from typing import Any, Callable, Dict, List, Optional, TypeVar

from azure.core import AsyncPipelineClient
from azure.core.exceptions import (
    HttpResponseError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import AsyncHttpResponse, HttpRequest
from azure.core.tracing.decorator_async import distributed_trace_async
from azure.core.utils import case_insensitive_dict

from ... import models as _models
from ..._utils.model_base import SdkJSONEncoder, _deserialize
from ..._utils.serialization import Deserializer, Serializer

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, Dict[str, Any]], Any]]
JSON = MutableMapping[str, Any]

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False


def build_models_list_request(**kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})

    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    accept = _headers.pop("Accept", "application/json")

    _url = "/asset-gallery/v1.0/models"

    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="POST", url=_url, headers=_headers, **kwargs)


class ModelsOperations:
    """Async ModelsOperations operations.

    You should not instantiate this class directly. Instead, use the async
    :class:`~azure.ai.catalog.aio.CatalogClient`.
    """

    def __init__(self, client: AsyncPipelineClient, config: Any, serializer: Serializer, deserializer: Deserializer) -> None:
        self._client = client
        self._config = config
        self._serialize = serializer
        self._deserialize = deserializer

    @distributed_trace_async
    async def list(
        self,
        *,
        filters: Optional[List[Dict[str, Any]]] = None,
        order_by: Optional[str] = None,
        page_size: Optional[int] = None,
        **kwargs: Any,
    ) -> List[_models.ModelSummary]:
        """Search for models in the Azure AI model catalog.

        :keyword filters: A list of filter dicts.
        :paramtype filters: list[dict[str, Any]]
        :keyword order_by: Field name to order results by.
        :paramtype order_by: str
        :keyword page_size: Maximum number of results to return.
        :paramtype page_size: int
        :return: List of ModelSummary
        :rtype: list[~azure.ai.catalog.models.ModelSummary]
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: lambda *a, **kw: HttpResponseError(*a, **kw),
            404: lambda *a, **kw: HttpResponseError(*a, **kw),
            409: lambda *a, **kw: HttpResponseError(*a, **kw),
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type: str = kwargs.pop("content_type", _headers.pop("Content-Type", "application/json"))
        cls: ClsType[List[_models.ModelSummary]] = kwargs.pop("cls", None)

        body: Dict[str, Any] = {}
        if filters is not None:
            body["filters"] = filters
        if order_by is not None:
            body["order"] = [{"field": order_by, "direction": "Desc"}]
        if page_size is not None:
            body["pageSize"] = page_size

        _content = json.dumps(body, cls=SdkJSONEncoder)

        _request = build_models_list_request(
            content_type=content_type,
            content=_content,
            headers=_headers,
            params=_params,
        )
        _request.url = self._client.format_url(_request.url)

        _stream = False
        pipeline_response: PipelineResponse = await self._client._pipeline.run(  # type: ignore  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = response.json()
        summaries = deserialized.get("summaries", [])
        result = _deserialize(List[_models.ModelSummary], summaries)

        if cls:
            return cls(pipeline_response, result, {})  # type: ignore

        return result
