# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from typing import Any

from azure.core.pipeline import policies

from .._version import VERSION


class CatalogClientConfiguration:  # pylint: disable=too-many-instance-attributes
    """Configuration for async CatalogClient.

    :param base_url: Service host. Default value is "https://api.catalog.azureml.ms".
    :type base_url: str
    :keyword api_version: The API version to use. Default value is "v1.0".
    :paramtype api_version: str
    """

    def __init__(
        self,
        base_url: str = "https://api.catalog.azureml.ms",
        **kwargs: Any,
    ) -> None:
        api_version: str = kwargs.pop("api_version", "v1.0")

        self.base_url = base_url
        self.api_version = api_version
        kwargs.setdefault("sdk_moniker", "ai-catalog/{}".format(VERSION))
        self._configure(**kwargs)

    def _configure(self, **kwargs: Any) -> None:
        self.user_agent_policy = kwargs.get("user_agent_policy") or policies.UserAgentPolicy(**kwargs)
        self.headers_policy = kwargs.get("headers_policy") or policies.HeadersPolicy(**kwargs)
        self.proxy_policy = kwargs.get("proxy_policy") or policies.ProxyPolicy(**kwargs)
        self.logging_policy = kwargs.get("logging_policy") or policies.NetworkTraceLoggingPolicy(**kwargs)
        self.http_logging_policy = kwargs.get("http_logging_policy") or policies.HttpLoggingPolicy(**kwargs)
        self.custom_hook_policy = kwargs.get("custom_hook_policy") or policies.CustomHookPolicy(**kwargs)
        self.redirect_policy = kwargs.get("redirect_policy") or policies.AsyncRedirectPolicy(**kwargs)
        self.retry_policy = kwargs.get("retry_policy") or policies.AsyncRetryPolicy(**kwargs)
        self.authentication_policy = kwargs.get("authentication_policy")
